### ISSUE TITLE
Install Docs In Readme Out Of Date

### ISSUE THREAD

**Issue by ebebbington** [nestdotland/eggs#102]
## 📚 Documentation Issue

https://github.com/nestdotland/eggs#install

`cli.ts` needs to be replaced with `eggs.ts` (i assume 0.3.0 made this change)

**Comment by SteelAlloy** [comment]
This is not a mistake, this is the `eggs install` command 😉
Although little used, it is very useful
https://docs.nest.land/eggs/installing-a-script-as-an-executable.html

**Comment by ebebbington** [comment]
🤦
