### ISSUE TITLE
`eggs publish` Fails with Deno v1.6.0

### ISSUE THREAD

**Issue by ebebbington** [nestdotland/eggs#109]
## 🐛 Bug Report

When running `eggs publish` on deno v1.6.0, `eggs publish fails with the following error: 

![image](https://user-images.githubusercontent.com/47337480/101615009-8c6af780-3a05-11eb-9148-8ddfe177ddee.png)

## To Reproduce

The steps taken. are here: 

```
runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
        repository: drashland/${{ github.event.client_payload.repo }}
    - uses: denolib/setup-deno@master
    - run: |
        deno install -A -f --unstable -n eggs https://x.nest.land/eggs@0.3.2/eggs.ts
        export PATH="/home/runner/.deno/bin:$PATH"
        eggs link ${{ secrets.CI_NESTLAND_API_KEY }}
        eggs publish --no-check-tests --yes
```

## Expected behavior

I understand eggs hasn't been updated, so it's not like i'm expecting this to just work. This issue is more to bring it to your attention. On deno v1.6.0 (eggs v0.3.3?), publishing should work

## Actual Behavior

Publishing failed due to a compiling error

## Environment

- Eggs version: 0.3.2
- Deno version: v1.6.0
- Operating system and version: ubuntu-latest

**Comment by maximousblk** [comment]
This is again a cliffy bug, we're moving away from cliffy in the new cli.

relevant cliffy issue: https://github.com/c4spar/deno-cliffy/issues/121

**Comment by ebebbington** [comment]
Does cliffy use unversioned imports then? Cause I’m guessing nothing should have changed as eggs or cliffy hasn’t released a new version?

**Comment by maximousblk** [comment]
It's because Deno 1.6 is shipped with TS 4.1 which has some changes in the promise types

**Comment by ebebbington** [comment]
ah yeah course, i'm getting myself confused - np. then! Again, thanks for the super fast replies :P Really helpful when this happens :)

**Comment by SteelAlloy** [comment]
I'm reopening this issue
I'll close it when eggs is working with Deno 1.6!

**Comment by oganexon** [comment]
#111
