### ISSUE TITLE
[BUG] Progress bar after publishing

### ISSUE THREAD

**Issue by t8** [nestdotland/eggs#11]
**Describe the bug**
It appears that the progress bar on macOS is left incomplete and positioned in the wrong place after a publishing job is complete.

**To Reproduce**
`eggs publish`

**Expected behavior**
The progress bar should be placed above the confirmation text and appear as 100% after publishing

**Screenshots**
![image](https://user-images.githubusercontent.com/20846869/87253865-9daada80-c44c-11ea-8979-0f8cfcb075c2.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - nest.land Version: 0.1.9 (the latest version that hasn't been published to nest.land yet)

**Comment by SteelAlloy** [comment]
I know where the problem lies, folks (at least I think)
You must not use a `console.log` with the bar, you must use `progress.console`
Else things break 

But it also appears that 21/23 tasks has been completed 
Might be related

**Comment by martonlederer** [comment]
@oganexon i think i used that function

**Comment by SteelAlloy** [comment]
Sorry then, I struggle on my phone to follow the changes 
It must the 21/23 then

**Comment by t8** [comment]
Fixed in #7
