### ISSUE TITLE
CLI ignoring DENO_DIR environment variable

### ISSUE THREAD

**Issue by hqnna** [nestdotland/eggs#118]
## 🐛 Bug Report

When using the `eggs` cli, it tends to ignore the `DENO_DIR` variable occasionally, such as put "hatcher" files in `$HOME/.deno` while as `DENO_DIR` is being set to `$HOME/.local/deno` 

## To Reproduce

1. Set the `DENO_DIR` environment variable in your `.zshrc` or equivalent file
2. Install eggs normally through the command seen in the documentation
3. You'll notice that eggs was installed to `$HOME/.deno` and not where the variable is set

## Expected behavior

It should be follow the `DENO_DIR` variable for installation and other operations

## Actual Behavior

It installs into `$HOME/.deno` despite the variable being set

![screenshot](https://egg.lgbt/i/yo3kcfxw.png)

## Environment

- Eggs version: 0.3.5
- Deno version: 1.7.5 (release, x86_64-unknown-linux-gnu)
- Operating system and version: Arch Linux on WSL (4.19.128-microsoft-standard)

**Comment by maximousblk** [comment]
as stated in the deno help (`deno -h`) `DENO_DIR` is a directory for build and dependency cache. maybe you're looking for `DENO_INSTALL_ROOT`?

![image](https://user-images.githubusercontent.com/28438021/109925565-eec35380-7ce7-11eb-9ad7-e8007f153b8a.png)

also, this is not a problem with eggs.

**Comment by maximousblk** [comment]
closing
