### ISSUE TITLE
Support import maps and/or add "dependenciesFile" key to config

### ISSUE THREAD

**Issue by nnmrts** [nestdotland/eggs#119]
## 🚀 Feature

Add support for [import maps](https://github.com/WICG/import-maps) like [Deno does](https://deno.land/manual@v1.8.1/linking_to_external_code/import_maps), more specifically to the `eggs update` command. There may be other commands that could profit from this too.

## Motivation

I don't use Typescript or even JavaScript module files, instead I use a `modules.json` file as an import map, which is supported by Deno (and Chrome I think) and will be (fingers crossed) standard soon. There is currently no way for me to update my dependencies through the eggs CLI, unless I switch to a .ts or .js file.

## Implementation

A simple and hopefully fast solution would be to add JSON support to the `eggg update` command, more specifically to the `--file` option.

But I personally think it would be good to add a key like `dependenciesFile` to the egg config schema, so one doesn't have to use the `--file` option every time they want to update their dependencies just because they named their dependencies file something other than the default (and - to be fair - opinionated) `"deps.ts"`.

## Alternatives

I think `dependenciesFile` is a descriptive, but pretty long key. However, I couldn't come up with a better key yet, `dependencies` for example seems to vague, just `file` seems misleading, which is why I would also suggest to change the name of the CLI option. Maybe `depFile`? `importsFile`? `modulesFile`?

**Comment by maximousblk** [comment]
Import maps should not be used as a primary way to manage dependencies. Import maps are not composable and make it harder to use for the user

Quote from [deno 1.8 release post](https://deno.land/posts/v1.8#import-maps-are-now-stable)

> Users should keep in mind that import maps are not composable: this means you can only provide a single import map to `deno run` / `deno test`. Because of this library authors should still use regular, non-bare specifiers (relative or absolute file / http URLs); otherwise the users of the library will manually need to add your libraries (and your libraries dependencies) bare specifiers into their import map.
> 
> A much more useful feature for import maps is ability to remap regular specifiers to completely different ones. For example if you have some broken dependency that is deeply nested in your module graph you can replace it with fixed version before it's fixed upstream, or if you use a build process that adds hashes to your modules filenames, you can refer to the file without hashes in your source code and remap the specifiers only at runtime using an import map.

**Comment by maximousblk** [comment]
Import maps are not composable and should not be used for dependency management

Quote from deno [1.8 release notes](https://deno.land/posts/v1.8#import-maps-are-now-stable):

> Users should keep in mind that import maps are not composable: this means you can only provide a single import map to `deno run` / `deno test`. Because of this library authors should still use regular, non-bare specifiers (relative or absolute file / http URLs); otherwise the users of the library will manually need to add your libraries (and your libraries dependencies) bare specifiers into their import map.
> 
> A much more useful feature for import maps is ability to remap regular specifiers to completely different ones. For example if you have some broken dependency that is deeply nested in your module graph you can replace it with fixed version before it's fixed upstream, or if you use a build process that adds hashes to your modules filenames, you can refer to the file without hashes in your source code and remap the specifiers only at runtime using an import map.

If this is not what you meant, can you link to an example of how you're managing your dependencies using import maps?

**Comment by nnmrts** [comment]
I'm not a native english speaker, so I'm not a 100% sure, but do these two paragraphs basically say that if I write a library which imports, idk, "cliffy.ts", but through an import map, so its actually using only "cliffy" in my code, anyone using my library would not be able to run this code without providing an import map themselves?

Well, if so, then that's unfortunate, didn't know that. But it actually makes sense, compared to node, but there it's just automated through `npm install` I guess.

But alright, thanks for pointing me to that info in the release notes, I will switch to a `modules.js` or `dependencies.js` file, everything in eggs should be fine with that.

I still think the `--file` option is a bit confusing and a config key would be nice though, but that's another issue after all.

**Comment by maximousblk** [comment]
Yes that is correct. Basically if you use import maps for dependency management, the ser will have to use your import map to use your module. And if many modules use this method, the user will have to use multiple import maps, which is not possible.

The current community convention is to use a `deps.ts` or `deps.js` file and keep it in the root directory to make it easier for the user to check which dependencies you are using.

If you have further questions we'd love to answer them in [our Discord server](https://discord.gg/hYUsX3H)
