### ISSUE TITLE
egg.json `$schema:` url `@` gets escaped in vscode

### ISSUE THREAD

**Issue by josh-hemphill** [nestdotland/eggs#125]
## 🐛 Bug Report

Adding a `$schema` reference url in your `egg.json` results in VS Code trying to resolve with the `@` symbol url escaped as `%40`

e.g.
```jsonc
{
  "$schema": "https://x.nest.land/eggs@0.3.1/src/schema.json",
  // Unable to load schema from 'https://x.nest.land/eggs%400.3.1/src/schema.json': Request vscode/content failed unexpectedly without providing any details.(768)
  "name": "module-name"
}
```

## To Reproduce

1. create `egg.json`
2. open in VS Code
3. Add `$schema` reference listed in docs

## Expected behavior

Urls with escaped `@` symbols should still resolve

## Actual Behavior

Returns error message

## Environment

- Eggs version:
- Deno version: 1.10.2
- Operating system and version: WSL2, Ubuntu 20.04

**Comment by maximousblk** [comment]
Hey @josh-hemphill!

Sorry for the late reply. for now, you can use github raw url to the schema. we'll probably make this the default in new releases. we can't fix this on nest because we don't support untagged links so the `@` has to be there.

github raw url to schema:

```sh
# tagged
https://github.com/nestdotland/eggs/raw/0.3.7/src/schema.json

# latest
https://github.com/nestdotland/eggs/raw/master/src/schema.json

# dev
https://github.com/nestdotland/eggs/raw/dev/src/schema.json
```
