### ISSUE TITLE
`eggs publish` hangs in Powershell

### ISSUE THREAD

**Issue by GJZwiers** [nestdotland/eggs#129]
## 🐛 Bug Report

`eggs publish` hangs when run in Powershell and keeps displaying the line `[INFO] Ôáª Checking if the source files are formatted...`

## To Reproduce

1. install `eggs` on windows
2. go to a module entrypoint like `mod.ts`
3. run `eggs publish` either with arguments or by making an `egg.json` file first
4. issue happens

## Expected behavior

Successfully performs check if source files are formatted and proceeds with tests and module publish.

## Actual Behavior

Keeps displaying `[INFO] Ôáª Checking if the source files are formatted...`. 

## Environment

- Eggs version: `0.3.8`
- Deno version:
```
deno 1.11.4 (release, x86_64-pc-windows-msvc)
v8 9.1.269.35
typescript 4.3.2
```
- Operating system and version: `Windows 10, Version 10.0.19041 Build 19041`

## Additional context

I run Windows with WSL2 installed, If I publish my module from the Linux system everything works as expected and afterwards I can run `eggs publish` on Powershell or cmd and it will not hang on the formatting but behave as expected (runs the tests and notices the module version is already is already published)

**Comment by SteelAlloy** [comment]
Hi
This problem has already been encountered on Windows, but unfortunately it is out of our control.
However, you can use the `--check-format false` option to disable this check or the `--no-check` option to disable all checks.
You can also set these options in your config file.

If you still need to check the formatting of your files, you will have to do it with a separate command.

**Comment by GJZwiers** [comment]
Hi, thanks for the reply! I've tried it with the options and that seems to be working. As mentioned before I can also run it fine from a Linux shell. Thanks for taking the time, I will close the issue now.
