### ISSUE TITLE
Add .eggignore file and allow users to chose between the ignore file or the files field in egg.json

### ISSUE THREAD

**Issue by martonlederer** [nestdotland/eggs#3]
**Is your feature request related to a problem? If so, please describe.**
Right now the nest.land CLI publishes only the files given in the `files` field, in `egg.json`. Sometimes people have a lot of files imported from various directories and it's hard to keep track of all of them.

Also if you create a new file it is extra time to add it to the `files` field.

**Describe the solution you'd like**
The best solution would be to let the users choose between the `files` field or a `.eggignore` file. If the `.eggignore` file extists, the cli uses it instead of the `files` field.

**Describe alternatives you've considered**
An alternative already exists, using `*`

**Comment by t8** [comment]
Closing now, as this has already been implemented and merged into `dev`.
