### ISSUE TITLE
feat: deprecate the stable field and enforce semver

### ISSUE THREAD

**Issue by Keimeno** [nestdotland/eggs#44]
**Is your feature request related to a problem? If so, please describe.**
There's no use in setting the `stable` field configuration by hand.

**Describe the solution you'd like**
eggs should remove the ability to set the stability manually. It should be detected by the it's semantic version. As they have a specification for what is called stable or unstable/a pre-release.

**Comment by t8** [comment]
Hi @Keimeno! Thanks for reaching out. This is actually quite a hot topic of discussion. We have some people that share your perspective on the matter, but we have others saying that the version doesn't show stability. My personal opinion is that we can't assume stability based on the version just because of the following example: Deno's `std` library is currently at version 0.61.0, but they are still considered "unstable."

I'm interested to hear what you have to say about this, but I personally don't believe we can use semantic versioning to detect stability.

**Comment by SteelAlloy** [comment]
@t8 std follows semver 🙂 
https://semver.org/#spec-item-4
"Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable"

**Comment by Keimeno** [comment]
Another problem with the current approach is, we are not enforcing a versioning standard. Meaning we could use CalVer, or anything else as well.

Also npm and yarn enforce SemVer. And with that, the majority of Javascript developers are familiar with it. So there's no reason to leave this unspecified, as it supports unification and makes working with different versions easier.

**Comment by Keimeno** [comment]
To name a few examples of libraries, that do not implement the SemVer specifications, because it isn't enforced are:
* [validasaur](https://nest.land/package/validasaur) does not follow SemVer and adds a v- prefix in front of its version
* [denon](https://nest.land/package/denon) did not turn on the stable release manually, and now version 2.2.1 is considered unstable by nest.land.
* [orange](https://nest.land/package/Orange) which flagged it's 0.2.7 release as stable. Which should not be the case. 

It will also make the stable and latest buttons on each project more logical. Since the spec also defines the method to sort the versions and retrieve the latest stable, and the latest overall release [here](https://semver.org/#spec-item-11).

**Comment by t8** [comment]
Thanks for the correction, @oganexon. 😄 

I see what you're saying, @Keimeno, but this has been done on purpose in efforts not to limit the user or enforce a standard. The fact that we have different modules using different formats of versioning already proves the validity of the `stable` field. I wouldn't be against investigating a solution to automatically determine the stability for a module using SemVer though.

@zorbyte, what are your opinions on this?

**Comment by zorbyte** [comment]
Versions have dash specifiers for whether or not something is stable. We should use SemVer

**Comment by SteelAlloy** [comment]
#58 The version field  is now determined according to the SemVer rules
