### ISSUE TITLE
Validate that the package can be correctly installed

### ISSUE THREAD

**Issue by tranzystorekk** [nestdotland/eggs#53]
**Is your feature request related to a problem? If so, please describe.**
Especially when publishing global scripts, it is easy to miss files in the `egg.json`, whether due to simple forgetting, file renames etc.

**Describe the solution you'd like**
A `validate` subcommand that verfies that the package defined in eggs.json can be correctly installed would be helpful to test the package manually (or automatially) before publishing.

The technical details should be further discussed, but some sort of simulated installation would be a good general directon.

**Describe alternatives you've considered**
This could also be a flag to the `publish` command.

**Comment by littledivy** [comment]
+1 for this, it could also be extended where users could get pre-publish module analysis from our nest_analyzer.
