### ISSUE TITLE
Entry file displayed as `mod.ts`, even though it is set to something else.

### ISSUE THREAD

**Issue by mjrlowe** [nestdotland/eggs#54]
This is the same issue that I previously described in nestdotland/nest.land#185, but that was fixed by @MartonDev in nestdotland/nest.land#184. 
It seems  that exactly the same problem is happening again (see [here](https://nest.land/package/maze_generator)), despite the entry file still being set to something else (in this case `mod.js`) in `egg.json`.

**Comment by SteelAlloy** [comment]
Fixed in #55.
