### ISSUE TITLE
extend .eggignore with a particular syntax

### ISSUE THREAD

**Issue by littledivy** [nestdotland/eggs#66]
**Is your feature request related to a problem? If so, please describe.**
While working on a particular project, I almost published my keyfile to nest.land :fearful: 
I had forgot to setup my `.eggignore` like my `.gitignore`

**Describe the solution you'd like**
A new, easy to implement syntax for `.eggignore`

```sh
extends .gitignore

./other/files/to/ignore
```

**Describe alternatives you've considered**
Copy paste my gitignore to eggignore

**Comment by SteelAlloy** [comment]
It's a very good idea, it avoids making duplicates.

I was wondering about this feature, if neither the `files` field, nor the `ignore` field nor the `.eggignore` file exist, would it be a good idea to take the values of the `.gitignore` file as a last resort?
This would only be the case if the configuration really doesn't specify any files.
And if `.gitignore` doesn't exist then `eggs` issues an error as usual

**Comment by SteelAlloy** [comment]
> 
> I was wondering about this feature, if neither the `files` field, nor the `ignore` field nor the `.eggignore` file exist, would it be a good idea to take the values of the `.gitignore` file as a last resort?
> This would only be the case if the configuration really doesn't specify any files.
> And if `.gitignore` doesn't exist then `eggs` issues an error as usual

@t8  I would like to have your opinion on this
For instance in the case of eggs, the .eggignore and .gitignore files are identical.

**Comment by t8** [comment]
I think that it would be beneficial to use a `.gitignore` if nothing else is present, but the user should specifically state that it should be used instead. Perhaps this could be a command line argument?

We want to avoid any opportunities for something to go wrong because of a misunderstanding on how to use the platform. Explicitly stating that a user wants to use a gitignore would be a way to prevent any unintended operations.

**Comment by SteelAlloy** [comment]
Sounds good
Then with the current system and this new syntax, it could look like `--ignore="extends .gitignore"`

**Comment by t8** [comment]
If I'm understanding correctly, you may not even need the `extends`. Perhaps a user could just pass in the location of the `.gitignore`?

**Comment by SteelAlloy** [comment]
It's a bit more complicated than that
Let's consider the following `.eggignore` file:
```ignore
.vscode/
nestkey.json
```
It is equivalent to the following command:
```sh
eggs publish --ignore .vscode/ nestkey.json
```
The arguments of `--ignore` are in fact the lines that an .eggignore file could contain

So let's consider another file:
```ignore
extends .gitignore
extends ./dir/file
```
It is equivalent to the following command:
```sh
eggs publish --ignore "extends .gitignore" "extends ./dir/file"
```
I think it's pretty consistent, but you have to tell me if it's not.

I'd prefer to add the keyword `extends` to the `ignore` language than to add a parameter to the `eggs publish`
