### ISSUE TITLE
Getting "[ERR] No /mod.ts found in config. An entry file is required." when the entry file is not mod.ts.

### ISSUE THREAD

**Issue by mjrlowe** [nestdotland/eggs#77]
**Describe the bug**

In eggs version 0.2.2, whatever I set the `entry` property to in the `egg.json` (or `egg.yaml`) file, I get the following error when running `eggs publish`: 
`[ERR] No /mod.ts found in config. An entry file is required.`
This happens whether there is an `entry` property; whether the the entry file mentioned exists; whether there is a  `./`, `/` or nothing preceding the file name; whether the file extention is `.js` or `.ts` ~~and whether the entry file is set to `mod.ts` or something else~~ _(actually I only get this problem when the entry file isn't `mod.ts`)_.

All the other properties seem to be working fine (I only get errors about not having a name, description or version if they aren't included in egg.json) but for some reason it never seems to pick up on the `entry` property.

 **To Reproduce**

I am using Windows 10, Deno 1.4.1, Eggs 0.2.2.  It seems to be happening with any eggs project.

**Comment by SteelAlloy** [comment]
Hi @TheWizardBear 
Did you include your entry file in the `files` field? / or did you ensure it's not matched by an `ignore` entry?

**Comment by SteelAlloy** [comment]
If this is indeed the case, it would be a good idea to add automatically the entry file to the uploads

**Comment by mjrlowe** [comment]
> Did you include your entry file in the `files` field? / or did you ensure it's not matched by an `ignore` entry?

@oganexon There was no `ignore` property although it turns out I was missing the `mod.ts` file in the `files` field, and adding it in fixed the problem when `entry` was set to `"/mod.ts"`. 

However, when the entry file is anything other than `mod.ts` I get this problem even when the file is included in `files`.

~~This is probably related somehow to #54 and nestdotland/nest.land#185.~~

**Comment by SteelAlloy** [comment]
Fixed in #79 
`--entry` was set by default to `mod.ts` and was overwriting the `entry` field in the config file
