### ISSUE TITLE
Running tests and formatting for publish command

### ISSUE THREAD

**Issue by ebebbington** [nestdotland/eggs#78]
Both a bug and a feature request.

**Is your feature request related to a problem? If so, please describe.**
1. I run `eggs publish`

2. Formatting the code takes a long time because it is formatting everything. Problem is i have node_modules and other files that are actually completely unrelated to what i'm publishing (this is problem 1)

3. When the publish command runs tests, it fails for me. Reason for this is because the command eggs uses to test, isn't what I use - eggs is running tests on files it shouldn't

I'm sure i won't only experience these problems - maybe other modules use `cd tests/some/dir && deno test`

**Describe the solution you'd like**
This is to propose a few things:

1. Only format files specified in the `egg.json`. I think this makes sense as i assume nest wants the. files formatted so when people check out the module on nest.land, it looks pretty - but they would only be seeing the files specified from `egg.json`

2. Allow a user to maybe customise the test command, or maybe a new field/property in `egg.json` that either specifies the directory or test command to run

3. Send to stdout **before** eggs starts formatting, because like i said, it took about a minute or more for me, so i was starting to assume the command was broken (problem 2), for. example, to. test my deno files, i. do `cd tests/deno && deno test -A`, whereas the `publish` command does `deno test -A --unstable`. I also believe. using the `--unstable` flag **should be optional**, because that command could break whenever, meaning modules that don't need it cant be published as the cli will error (possible problem 3)

**Describe alternatives you've considered**
None

**Additional context**
The repo i want to publish: https://github.com/ebebbington/context-finder

This repo is a project for both Node and Deno, hence the node_modules and other unrelated js code - there's a deno and node variant for everything, which is why it's problematic that the publish command runs `deno test` and `deno fmt` at the root directory

**Comment by SteelAlloy** [comment]
Solution 3 implemented
![spinner](https://user-images.githubusercontent.com/52361520/93689342-1a51d900-face-11ea-9d62-d2995d0b0103.gif)

**Comment by SteelAlloy** [comment]
Solution 1 & 2 implemented

**Comment by ebebbington** [comment]
spinners ❤️
