### ISSUE TITLE
[BUG] 48 Errors while running eggs upgrade

### ISSUE THREAD

**Issue by michael-spengler** [nestdotland/eggs#80]
being on deno version 1.4.0

![Screen Shot 2020-09-20 at 1 06 49 PM](https://user-images.githubusercontent.com/43786652/93709906-8bcb6f00-fb42-11ea-8d0b-9b1aa8d44e97.png)

**Comment by SteelAlloy** [comment]
I can't do anything about this sadly 😕
eggs@0.2.1 is broken on deno 1.4.x so you can't use it to upgrade to eggs@0.2.2
(but you can upgrade to eggs@0.2.2 on deno 1.3.x)
You have to install the latest version manually:
```sh
deno install -A -f --unstable -n eggs https://x.nest.land/eggs@0.2.2/mod.ts
```

**Comment by michael-spengler** [comment]
ok - thanks @oganexon
