### ISSUE TITLE
NEAT1 support

### ISSUE THREAD

**Issue by justablob** [nestdotland/eggs#94]
We're implementing NEAT1, a new approach to API token storage, on the server-side, which will require some changes to eggs too. Here's some information about NEAT1 (first draft): https://github.com/nestdotland/x/blob/5391c04b4e1d28115a22f8f7821083cb2bef7edb/NEAT1-details.txt

In short, Eggs now needs to store both the API key and the username to successfully publish modules. I'm working on a backwards-compatible approach which would allow most users to switch over seamlessly. 

Details will be added along the way

**Comment by maximousblk** [comment]
Closing in favor of Deno's bearer token based auth. We might look into this in the future if we need to
