### ISSUE TITLE
During deno install -A -f --unstable -n eggs https://x.nest.land/eggs@0.2.3/mod.ts I got the following errors

### ISSUE THREAD

**Issue by michael-spengler** [nestdotland/eggs#96]
Coming from: https://docs.nest.land/eggs/installation.html -->
deno install -A -f --unstable -n eggs https://x.nest.land/eggs@0.2.3/mod.ts

--> see screenshot
![Screen Shot 2020-10-21 at 21 08 32](https://user-images.githubusercontent.com/43786652/96771278-bc245880-13e1-11eb-97d4-7239905979cf.png)

**Comment by SteelAlloy** [comment]
Thank you for pointing out this problem.
What is your current Deno version ?
If you are on `1.4.6`, does it work with version `1.4.1` ?

In any case, `eggs@0.3.0` should solve these problems and will be released in the coming days 🙂

**Comment by michael-spengler** [comment]
@oganexon thank you very much. The account which I used was on a ridiculously old Deno version deno 1.1.0 :) - sorry for that --> 

if you like it, it might be a good idea to add a "Troubleshooting" section right before "Permissions used" https://docs.nest.land/eggs/installation.html#permissions-used

or something like: "Please ensure your deno version is above x.y.z"

**Comment by SteelAlloy** [comment]
@michael-spengler We already have something like this but it's maybe not sufficiently emphasized 😄

![image](https://user-images.githubusercontent.com/52361520/96776603-884d3100-13e9-11eb-9ad7-e9287efe3fd4.png)
